# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diamond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carat', models.DecimalField(decimal_places=2, max_digits=4)),
                ('clarity', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('cut', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
